---
title: C26111 |Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
caps.latest.revision: 10
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: 35fb02c425e5b8ad31df6082f4327f616664e559
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 11/16/2018
ms.locfileid: "51734742"
---
# <a name="c26111"></a>C26111
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

警告 C26111: 呼び出し元でロックを解放する失敗\<ロック > 関数を呼び出す前に\<func >。  
  
 注釈`_Requires_lock_not_held_`で関数が呼び出されたときに指定されたロックのロック数が 0 より大きいことはできませんが、前提条件が課せられます。 警告 C26111 別の関数を呼び出す前に、ロックの解除に失敗した関数が発行されます。  
  
## <a name="example"></a>例  
 次の例では、ため、警告 C26111 が生成されます、`_Requires_lock_not_held_`への呼び出しによって前提条件に違反して`DoNotLock`ロックされている範囲内で。  
  
```  
  
typedef struct _DATA   
{  
    CRITICAL_SECTION cs;  
    int d;  
} DATA;  
  
_Requires_lock_not_held_(p->cs)   
  
void DoNotLock(DATA* p)  
{  
    EnterCriticalSection(&p->cs);   
    p->d = 0;  
    LeaveCriticalSection(&p->cs);  
}  
  
void LockedFunction(DATA* p)   
{   
    EnterCriticalSection(&p->cs);   
    DoNotLock(p); // Warning C26111  
    LeaveCriticalSection(&p->cs);  
}  
  
```



