---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 47bb0843ab6048bbfa1b4ba881d3748a23de6dd9
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 10/16/2019
ms.locfileid: "72449646"
---
# <a name="c6318"></a>C6318
警告 C6318: 不適切に定義された __try/\__except: 定数 EXCEPTION_CONTINUE_SEARCH または例外フィルター式で0に評価される別の定数を使用しています。 例外ハンドラー ブロックのコードは実行されません

 この警告は、この構造化例外ハンドラーの保護されたブロックで例外が発生した場合に、例外フィルター式で定数 `EXCECPTION_CONTINUE_SEARCH` が使用されているため、例外が処理されないことを示します。

 このコードは、ハンドラーブロックが実行されないため、例外ハンドラーブロックのないプロテクトブロックに相当します。

## <a name="example"></a>例
 この警告が発生するコード例を次に示します。

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 この警告を解決するには、次のコードを使用します。

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>参照
 [try-except ステートメント](/cpp/cpp/try-except-statement)
