---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 5a67173e7621204122a26c2b0ebe632eb01000d0
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/23/2019
ms.locfileid: "62781672"
---
# <a name="c6312"></a>C6312
C6312 を警告します。無限ループ: の例外フィルター式で定数 EXCEPTION_CONTINUE_EXECUTION の使用-以外

 この警告は、定数の`EXCEPTION_CONTINUE_EXECUTION`(または-1 に評価される別の定数) 構造化例外ハンドラーのフィルター式で。 定数値の使用`EXCEPTION_CONTINUE_EXECUTION`無限ループが発生する可能性があります。 たとえば、ハードウェアによって例外が発生した場合、例外の原因となった命令が再起動されます。 例外の原因となったアドレスがまだ正しくない場合は、別の例外が発生し、同じ方法で処理します。 これにより、無限ループが発生します。

 明示的に呼び出す`RaiseException`無限ループでは、直接的にではありません原因しますが、保護されたブロックで引き続きコードを実行します。 これは、予期されることができ、場合、無限ループが発生する可能性`RaiseException`に無効なポインターを逆参照を回避するために使用されました。

 通常、`EXCEPTION_CONTINUE_EXECUTION`のみ、例外の原因となったポインターまたは基になるメモリのいずれかを解決する可能性のあるフィルター式で呼び出される関数によって返される必要があります。

## <a name="example"></a>例
 この警告が発生するコード例を次に示します。

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 この警告を解決するには、次のコードを使用します。

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```