---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 48f18934d1bf78a1764bd3ac7a7c8b7b64508ece
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 10/07/2019
ms.locfileid: "72017760"
---
# <a name="c6312"></a>C6312
警告 C6312:考えられる無限ループ: try の例外フィルター式での定数 EXCEPTION_CONTINUE_EXECUTION の使用 (except)

 この警告は、構造化例外ハンドラのフィルター式で、定数 `EXCEPTION_CONTINUE_EXECUTION` (または-1 に評価される別の定数) を使用していることを示します。 定数値 `EXCEPTION_CONTINUE_EXECUTION` を使用すると、無限ループにつながる可能性があります。 たとえば、ハードウェアによって例外が発生した場合、例外の原因となった命令が再起動されます。 例外の原因となったアドレスが依然として間違っている場合は、別の例外が発生し、同じ方法で処理されます。 これにより、無限ループが発生します。

 @No__t-0 を明示的に呼び出すと、無限ループは直接発生しませんが、保護されたブロック内のコードの実行は続行されます。 これは予期しない場合があります。 `RaiseException` を使用して無効なポインターが逆参照されないようにすると、無限ループが発生する可能性があります。

 通常、`EXCEPTION_CONTINUE_EXECUTION` は、フィルター式で呼び出された関数によってのみ返される必要があります。この場合、例外の原因となったポインターまたは基になるメモリを修正する機会があります。

## <a name="example"></a>例
 この警告が発生するコード例を次に示します。

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 この警告を解決するには、次のコードを使用します。

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```