---
title: C6312 |Microsoft ドキュメント
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: 766a3c670a41bb4f915c94c3f5d0df09fde11afe
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/16/2018
---
# <a name="c6312"></a>C6312
警告 C6312: 無限ループが発生している可能性があります: try-except の例外フィルター式で定数 EXCEPTION_CONTINUE_EXECUTION が使用されています。  
  
 この警告は、定数の使用を示します`EXCEPTION_CONTINUE_EXECUTION`(または別の定数を-1 に評価される) で構造化例外ハンドラーのフィルター式です。 定数値の使用`EXCEPTION_CONTINUE_EXECUTION`無限ループが発生する可能性があります。 たとえば、ハードウェアで例外が発生した、例外の原因となった命令が再開されます。 例外の原因となったアドレスがまだ正しくない場合は、別の例外が発生し、同じ方法で処理します。 これにより、無限ループが発生します。  
  
 明示的に呼び出す`RaiseException`直接原因、無限ループですが保護されたブロックでコードの実行が続行されます。 これは、予測不可能し、場合に無限ループが発生する可能性があります`RaiseException`に無効なポインターを逆参照を防ぐために使用されました。  
  
 通常、`EXCEPTION_CONTINUE_EXECUTION`いずれかの例外の原因となったポインターまたは基になるメモリを解決する可能性のあるフィルター式で呼び出す関数からのみ返される必要があります。  
  
## <a name="example"></a>例  
 この警告が発生するコード例を次に示します。  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 この警告を解決するには、次のコードを使用します。  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```