---
title: C6318
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 73dae483e22b486b9204df97958966e83da66527
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/26/2018
---
# <a name="c6318"></a>C6318
C6318 を警告します。 正しく定義されていない _ _try/\__except: 定数 EXCEPTION_CONTINUE_SEARCH または例外フィルター式で 0 に評価される別の定数を使用します。 例外ハンドラー ブロックのコードは実行されません

 この警告は、この構造化例外ハンドラーの保護されたブロックで例外が発生する場合、例外は処理されませんのでを示します定数`EXCECPTION_CONTINUE_SEARCH`例外フィルター式で使用されます。

 このコードは、ハンドラー ブロックが実行されないため、例外ハンドラー ブロックせず保護ブロックと同じです。

## <a name="example"></a>例
 この警告が発生するコード例を次に示します。

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 この警告を解決するには、次のコードを使用します。

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>関連項目
 [try-except ステートメント](/cpp/cpp/try-except-statement)